### ISSUE TITLE
Missing Component in CakeDC plugin(cakephp 3.0)

### ISSUE THREAD

**Issue by kailash91** [CakeDC/search#202]
Search.PrgComponent could not be found.

Make sure your plugin was loaded from config\bootstrap.php and Composer is able to autoload its classes, see Loading a plugin and Plugins - autoloading plugin classes

**Comment by pmoraes** [comment]
Hello @kailash91, 

I tried to reproduce your problem here and I don't got success, could you explain it better?

**Comment by ajibarra** [comment]
@kailash91 Search plugin is not compatible with Cake 3 yet. We will announce once it is done. Thanks for using and supporting the plugin

**Comment by Marlinc** [comment]
@kailash91 are you using the 3.0 branch of the plugin?

**Comment by burzum** [comment]
The 3.0 branch of the plugin works OK, even with 3.1, but could still use some refactoring. Overall the plugin could use a massive overhaul. There are lots of things that could be done better now. However, we're using @dereuromark [fork of the plugin](https://github.com/dereuromark/search/tree/3.0) because it's better supported. An alternative to this plugin could be the [FoC search plugin](https://github.com/friendsofcake/search) I really like it's simplicity compared to this plugin here. What I don't like about it is it's API.
